### ISSUE TITLE
Can you share the method that how you compute the edge?

### ISSUE THREAD

**Issue by yjsb** [ZM-J/ET-Net#8]
I need the idea that how you compute the ground truth edge. And I want to expand the method in 3D space.
Your codes:

    def gradient(img):
      result_x = np.zeros_like(img, dtype=np.float)
      result_x[:, 0] = img[:, 1] - img[:, 0]
      result_x[:, 1:-1] = (img[:, 2:] - img[:, :-2]) / 2
      result_x[:, -1] = img[:, -1] - img[:, -2]

      result_y = np.zeros_like(img, dtype=np.float)
      result_y[0, :] = img[1, :] - img[0, :]
      result_y[1:-1, :] = (img[2:, :] - img[:-2, :]) / 2
      result_y[-1, :] = img[-1, :] - img[-2, :]

      return result_x, result_y

And then 

      gx, gy = gradient(gt)
      temp_edge = gx * gx + gy * gy
      temp_edge[temp_edge != 0] = 1
      temp_edge = (temp_edge * 255).astype(np.uint8)

How did you come up with that calculation? Please tell me.

**Comment by ZM-J** [comment]
I'm sorry, I have not applied this network to 3D space.

As for 2D circumstance, since we have the ground-truth labels, we can get edges by finding [morphological skeleton](https://en.wikipedia.org/wiki/Morphological_skeleton).

And I'm also sorry for having no time to maintain this repo 🥹

**Comment by yjsb** [comment]
Oh, very thanks. I will try my self. Thank you for sharing.
